styleguide: iJackUA/blog-phoenix-elixir
engines:
  credo:
    enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
    exclude_paths:
      - app/views/**/*
exclude_paths:
- config
- priv/repo
- test
